version: '3.9'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 150209
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
